const ORDER = {
  'bun': {
    "_id": "60d3b41abdacab0026a733c6",
    "name": "Краторная булка N-200i",
    "type": "bun",
    "proteins": 80,
    "fat": 24,
    "carbohydrates": 53,
    "calories": 420,
    "price": 1255,
    "image": "https://code.s3.yandex.net/react/code/bun-02.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
    "__v": 0
  },
  'others': [
    {
      "_id": "60d3b41abdacab0026a733c9",
      "name": "Мясо бессмертных моллюсков Protostomia",
      "type": "main",
      "proteins": 433,
      "fat": 244,
      "carbohydrates": 33,
      "calories": 420,
      "price": 1337,
      "image": "https://code.s3.yandex.net/react/code/meat-02.png",
      "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
      "__v": 0
    },
    {
      "_id": "60d3b41abdacab0026a733cb",
      "name": "Биокотлета из марсианской Магнолии",
      "type": "main",
      "proteins": 420,
      "fat": 142,
      "carbohydrates": 242,
      "calories": 4242,
      "price": 424,
      "image": "https://code.s3.yandex.net/react/code/meat-01.png",
      "image_mobile": "https://code.s3.yandex.net/react/code/meat-01-mobile.png",
      "image_large": "https://code.s3.yandex.net/react/code/meat-01-large.png",
      "__v": 0
    },
    {
      "_id": "60d3b41abdacab0026a733cc",
      "name": "Соус Spicy-X",
      "type": "sauce",
      "proteins": 30,
      "fat": 20,
      "carbohydrates": 40,
      "calories": 30,
      "price": 90,
      "image": "https://code.s3.yandex.net/react/code/sauce-02.png",
      "image_mobile": "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
      "image_large": "https://code.s3.yandex.net/react/code/sauce-02-large.png",
      "__v": 0
    },
    {
      "_id": "60d3b41abdacab0026a733d1",
      "name": "Плоды Фалленианского дерева",
      "type": "main",
      "proteins": 20,
      "fat": 5,
      "carbohydrates": 55,
      "calories": 77,
      "price": 874,
      "image": "https://code.s3.yandex.net/react/code/sp_1.png",
      "image_mobile": "https://code.s3.yandex.net/react/code/sp_1-mobile.png",
      "image_large": "https://code.s3.yandex.net/react/code/sp_1-large.png",
      "__v": 0
    },
    {
      "_id": "60d3b41abdacab0026a733d0",
      "name": "Хрустящие минеральные кольца",
      "type": "main",
      "proteins": 808,
      "fat": 689,
      "carbohydrates": 609,
      "calories": 986,
      "price": 300,
      "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
      "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
      "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
      "__v": 0
    },
    {
      "_id": "60d3b41abdacab0026a733d3",
      "name": "Мини-салат Экзо-Плантаго",
      "type": "main",
      "proteins": 1,
      "fat": 2,
      "carbohydrates": 3,
      "calories": 6,
      "price": 4400,
      "image": "https://code.s3.yandex.net/react/code/salad.png",
      "image_mobile": "https://code.s3.yandex.net/react/code/salad-mobile.png",
      "image_large": "https://code.s3.yandex.net/react/code/salad-large.png",
      "__v": 0
    },
    {
      "_id": "60d3b41abdacab0026a733d3",
      "name": "Мини-салат Экзо-Плантаго",
      "type": "main",
      "proteins": 1,
      "fat": 2,
      "carbohydrates": 3,
      "calories": 6,
      "price": 4400,
      "image": "https://code.s3.yandex.net/react/code/salad.png",
      "image_mobile": "https://code.s3.yandex.net/react/code/salad-mobile.png",
      "image_large": "https://code.s3.yandex.net/react/code/salad-large.png",
      "__v": 0
    },
    {
      "_id": "60d3b41abdacab0026a733d4",
      "name": "Сыр с астероидной плесенью",
      "type": "main",
      "proteins": 84,
      "fat": 48,
      "carbohydrates": 420,
      "calories": 3377,
      "price": 4142,
      "image": "https://code.s3.yandex.net/react/code/cheese.png",
      "image_mobile": "https://code.s3.yandex.net/react/code/cheese-mobile.png",
      "image_large": "https://code.s3.yandex.net/react/code/cheese-large.png",
      "__v": 0
    }
  ]
}

export { ORDER };
